# chatbot_task:
#   description: >
#     introduce yourself to the user and await thier question.
#     if the user asks a question, do not answer it, instead just repeat it back to them
#   expected_output: >
#     your introduction, or the question of the user repeat to them
#   agent: chatbot

scraping_task:
  description: >
    Go to Website and retrieve and collect all the content in it related to the query: {query},
    store it as plain text
  expected_output: >
    A detailed text of the related information in the website
  agent: scraper

query_resolver_task:
  description: >
    Review the context you got and make sure to simplify it, 
    every jargon or difficult thing should be converted into layman terms in your answer.
    Make sure the answer is easy to understand, short and concise.
  expected_output: >
    An easy to understand and concise answer, Formatted as markdown without '```'
  agent: query_resolver

# verifier_task:
#   description: >
#     Review the context you got, verify the terms present in it with the help of internet
#     make sure that the explainations are correct and accurate and form a report of the context
#     with corrections highlighted if any.
#   expected_output: >
#     A verified version of context in the form of a report, any corrections outlined
#     Formatted as markdown without '```'
#   agent: verifier
